# Generated by Django 3.1.2 on 2021-01-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'ordering': ['city'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='regions',
            options={'ordering': ['region'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
    ]
