# Generated by Django 3.1.2 on 2021-01-17 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Service')),
                ('description', models.TextField(blank=True, verbose_name='Service description')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Agencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(blank=True, max_length=100, verbose_name='Name of agency')),
                ('description', models.TextField(blank=True, verbose_name='Description of the agency')),
                ('address', models.CharField(blank=True, max_length=55, verbose_name='Address of the agency')),
                ('post_index', models.IntegerField(blank=True, default=0, max_length=5, verbose_name='Post index')),
                ('work_phone', models.CharField(blank=True, max_length=20, verbose_name='Work phone')),
                ('mobile_phone', models.CharField(blank=True, max_length=20, verbose_name='Mobile phone')),
                ('web_site', models.URLField(blank=True, verbose_name='Site')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, verbose_name='Rating')),
                ('logo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Logo')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.cities')),
                ('region', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.regions')),
                ('services', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='agency.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
            },
        ),
    ]
