# Generated by Django 3.1.2 on 2021-01-17 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(blank=True, verbose_name='Review text')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of publication')),
                ('mark', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=1, verbose_name='Mark')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agency.agencies', verbose_name='Agency')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.clients', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
