# Generated by Django 3.1.2 on 2021-01-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='mark',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, max_length=1, verbose_name='Mark'),
        ),
    ]
